apiVersion: v1
kind: ConfigMap
metadata:
  name: appProperties
data:
  appName: hello-world
  environment: test
  tier: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxConf
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Redirect Server Error Pages to the static Page /50x.html
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-map
spec:
  selector:
    matchLabels:
      app: config-map
  template:
    metadata:
      labels:
        app: config-map
    spec:
      volumes:
        - name: nginxConf
          configMap:
            name: nginxConf
        - name: appProperties
          configMap:
            name: appProperties
        - name: config
          projected:
            sources:
              - configMap:
                  name: nginxConf
              - configMap:
                  name: appProperties
      containers:
        - name: config-map-env
          image: busybox
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          command:
            - '/bin/sh'
            - '-c'
          args:
            - 'env && sleep 3600'
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: appProperties
                  key: app-version
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: appProperties
                  key: appName
            - name: TEAM
              valueFrom:
                configMapKeyRef:
                  name: appProperties
                  key: team
            - name: NGINX_CONF
              valueFrom:
                configMapKeyRef:
                  name: nginxConf
                  key: nginx.conf
