apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  revisionHistoryLimit: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world
      environment: test
      tier: frontend
  template:
    metadata:
      labels:
        app: hello-world
        environment: test
        tier: frontend
      annotations:
        kubernetes.io/change-cause: 'changed to v4'
    spec:
      containers:
        - name: hello-world
          image: amigoscode/kubernetes:hello-world-v4
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
