apiVersion: batch/v1
kind: Job
metadata:
  name: dbBackupJob
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: backup
          image: busybox
          command: ['/bin/sh', '-c']
          args:
            - "echo 'Performing DB Backup' && sleep 20"
      restartPolicy: Never
