apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret
spec:
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      volumes:
        - name: secret-1
          secret:
            secretName: appSecret
      containers:
        - name: secret
          image: busybox
          volumeMounts:
            - mountPath: /etc/secrets
              name: secret-1
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: appSecretFromFile
                  key: secret
          command:
            - 'sleep'
            - '3600'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
