apiVersion: v1
kind: Namespace
metadata:
  name: websites
  labels:
    author: michael-steinert
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-other-namespaces
  namespace: websites
spec:
  # Select all Pods
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-for-system-namespaces
  namespace: websites
spec:
  # Select all Pods
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name=websites: kube-system
        - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name=websites: ingress-nginx
